### ISSUE TITLE
need a "reset to defaults" button

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#174]
## Use Case

After users have dialed in a variety of settings, sometimes they just want to restore the default view/appearance

## Solution

A single button to accomplish this

## Alternatives

perhaps view/camera resets are separate from appearance/channel settings resets

**Comment by frasercl** [comment]
Should individual channel settings widgets also get a reset button? #80

**Comment by toloudis** [comment]
If they loaded a web link, do the settings in the link become the "reset" target settings?   "NO"
We want to reset to full defaults even if it undoes the settings from the link.

**Comment by ShrimpCryptid** [comment]
- For most viewer applications, resetting should reset ALL channel settings, even if it was opened from a URL.
- For links loaded from the landing page, it should honor those settings as the new default (through a flag in the URL or UI, or checking for location-based settings).

**Comment by ShrimpCryptid** [comment]
Reopning because #305 may not address original scope. Needs discussion with UX

**Comment by ShrimpCryptid** [comment]
Problem description:
- We should target having a single global reset. Reset channels AND advanced rendering settings
  - because it's global, may need to live higher on the UI
- Reset and links:
  - If users want to reset to the initial link view, they can just reopen the page or reload the link
  - Weird case where, from the landing page, we apply some initial settings (density - 2.5, etc.) => the user sees those as the initial default view, and resetting to the "true defaults" of the app will be different from the viewer's defaults.
  - CFE also applies some custom initial settings

UX discussion:
- Reset as a dropdown -> reset to default, reset to initial view
  - would be safer as a user to experiment with if there was an undo

**Comment by ShrimpCryptid** [comment]
- Any default OTHER than the initial view is a "new default" for the user. 
  - So maybe instead of "reset to defaults" it should say "Reset to Initial View" and take them **back to something familiar**.
  - The new user has no sense that the previous user has changed anything, or what has changed
- We can put a "Clear all ~~custom~~ settings" or something similar in the **Advanced Settings** panel
  - "Reset to default settings"
  - 💥 *explosion SFX*
  - Danger/warning icon
  - Tooltip or descriptive text, maybe a modal
- In the Share URL, include some extra information
  -  "The current view settings are saved in the URL"
