### ISSUE TITLE
reconcile the 3d axis position with the clipping sliders 

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#73]
## Use Case

we wanted the 3d clipping sliders to be at the bottom of the 3d view so they have a chance to have a wider space.
However, the 3d axis display is presented at the lower left, and when the Clipping drawer is open, it overlays on top and hides the axes.

## Solution

Not certain of the best solution.  
* I can make a strong argument for not overlaying and instead resizing the view.  (Same goes for the toolbar).  
* However it might be a nice option to be able to specify which corner the axes go in (as a prop maybe?).  
* Also possibly we can just shift the axes up when the drawer is open.

**Comment by lynwilhelm** [comment]
@frasercl @toloudis My thoughts on this are: 
I agree Dan that a strong argument can be made for toolbars NOT being overlays since the interactive area cannot be accessed when something lays over top of it anyway. Second best option for now (depending on dev effort/time) might be to keep with the overlay and somehow make the axis move with the clipping panel. Then, an item could be added to the [Research Repository](https://github.com/orgs/allen-cell-animated/projects/4/views/1) for suggesting toolbar and clipping panel do not overlay the interactive viewing area. Lastly, purely based on my experience with visual design, when I think of the axis in one of the upper corners it doesn't seem like it would feel anchored enough visually and it might interfere with the toolbar. Moving the axis up is my least favorite idea:)

**Comment by toloudis** [comment]
Bear in mind if we give the toolbar its own horizontal row at the top, the axis display won't interfere with it anymore.
```
[            ][toolbar]
| ctrl panel |[3d canvas]
[            ][clipping tools]
```

**Comment by lynwilhelm** [comment]
I meant interfere as smaller screen sizes, especially as toolbar items may grow
